workflows:
  android-debug-build:

    name: PocketDev APK Builder

    environment:
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.pocketdev"
      java: 17

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true

    scripts:

      - name: Set up Android SDK
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Accept licenses
        script: |
          yes | sdkmanager --licenses || true

      - name: Install SDK
        script: |
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Give permission to gradlew
        script: |
          chmod +x gradlew

      - name: Clean
        script: |
          ./gradlew clean

      - name: Build APK
        script: |
          ./gradlew :app:assembleDebug --no-daemon --stacktrace

    artifacts:
      - app/build/outputs/apk/debug/*.apk
